# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ships.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bships.proto\x12\x0cpackage.name\"\xe3\x03\n\x08Response\x1a\xa0\x02\n\x04Ship\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x11\n\tcrew_size\x18\x02 \x02(\x05\x12\x0e\n\x06length\x18\x03 \x02(\x02\x12\r\n\x05\x61rmed\x18\x04 \x02(\x08\x12\x33\n\talignment\x18\x05 \x02(\x0e\x32 .package.name.Response.Alignment\x12,\n\x06\x63lass_\x18\x06 \x02(\x0e\x32\x1c.package.name.Response.Class\x12\x35\n\x08officers\x18\x07 \x03(\x0b\x32#.package.name.Response.Ship.Officer\x1a>\n\x07Officer\x12\x12\n\nfirst_name\x18\x01 \x02(\t\x12\x11\n\tlast_name\x18\x02 \x02(\t\x12\x0c\n\x04rank\x18\x03 \x02(\t\x1a\x34\n\x06Galaxy\x12*\n\x05ships\x18\x01 \x03(\x0b\x32\x1b.package.name.Response.Ship\" \n\tAlignment\x12\x08\n\x04\x41lly\x10\x00\x12\t\n\x05\x45nemy\x10\x01\"\\\n\x05\x43lass\x12\x0c\n\x08\x43orvette\x10\x00\x12\x0b\n\x07\x46rigate\x10\x01\x12\x0b\n\x07\x43ruiser\x10\x02\x12\r\n\tDestroyer\x10\x03\x12\x0b\n\x07\x43\x61rrier\x10\x04\x12\x0f\n\x0b\x44readnought\x10\x05\"\x1e\n\x07Request\x12\x13\n\x0b\x63oordinates\x18\x01 \x01(\t2P\n\x07Greeter\x12\x45\n\x0bTransmitter\x12\x15.package.name.Request\x1a\x1d.package.name.Response.Galaxy\"\x00')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ships_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESPONSE._serialized_start=30
  _RESPONSE._serialized_end=513
  _RESPONSE_SHIP._serialized_start=43
  _RESPONSE_SHIP._serialized_end=331
  _RESPONSE_SHIP_OFFICER._serialized_start=269
  _RESPONSE_SHIP_OFFICER._serialized_end=331
  _RESPONSE_GALAXY._serialized_start=333
  _RESPONSE_GALAXY._serialized_end=385
  _RESPONSE_ALIGNMENT._serialized_start=387
  _RESPONSE_ALIGNMENT._serialized_end=419
  _RESPONSE_CLASS._serialized_start=421
  _RESPONSE_CLASS._serialized_end=513
  _REQUEST._serialized_start=515
  _REQUEST._serialized_end=545
  _GREETER._serialized_start=547
  _GREETER._serialized_end=627
# @@protoc_insertion_point(module_scope)
